formatting:
  NoWildcardImports:
    active: false

style:
  WildcardImport:
    active: false
  MagicNumber:
    active: true
    excludes: ['**/theme/**']

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated: ['Composable']